id: P009536
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25596
  title: མར་ངོའི་ཟླ་བ།
  author: ''
  volumes:
    3272c2dbbbb642f78c273668aa4261a7:
      image_group_id: I1KG25598
      title: ''
      volume_number: 1
      total_pages: 294
