id: P009536
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:36:58.046378
source_metadata:
  id: bdr:W1KG25596
  title: མར་ངོའི་ཟླ་བ།
  author: ''
  volumes:
    3272c2dbbbb642f78c273668aa4261a7:
      image_group_id: I1KG25598
      title: ''
      volume_number: 1
      total_pages: 294
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
